project:
  type: book

book:
  title: "Energy Data Analysis Application Module"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Franca Hollmann
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: en-US
  downloads: [pdf]
  repo-url: "https://github.com/bausteine-der-datenanalyse/a-energiedatenanalyse-en"
  repo-actions: [source]
  favicon: "skript/00-bilder/favicon_bcd_new.svg"
  sidebar:
    title: "Energy Data Analysis Application Module"
    logo: "skript/00-bilder/logo_with_text_new.svg"

## Inhaltsverzeichnis / table of contents
toc: true
toc-title:  |
  Energy Data Analysis Application Module 

  ![](skript/00-bilder/logo_with_text_new.svg)
number-sections: true
number-depth: 2

## Bibliographie / bibliography
bibliography: skript/bibliography.bib
biblio-style: authoryear

fig-width: 6
fig-asp: 0.618

format:
  html:
    theme: [cosmo, theme.scss]
    lang: en
    language:
      en:
        crossref-imp-title: "Definition"
        crossref-imp-prefix: "Definition"
        crossref-lst-title: "Code Block"
        crossref-lst-prefix: "Code Block"
        crossref-nte-title: "Example"
        crossref-nte-prefix: "Example"
        crossref-tip-title: "Tip"
        crossref-tip-prefix: "Tip"
        crossref-wrn-title: "Note"
        crossref-wrn-prefix: "Note"
        tbl-cap-location: bottom
  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    biblio-title: References
    lang: en
    toc-depth: 1

execute:
  freeze: auto

profile:
  default: full
  group: 
    - [full]
